# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_name', models.CharField(max_length=200)),
                ('registration_number', models.BigIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('picture', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='callname',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogdb.Dog'),
        ),
    ]
