# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NickNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='callname',
            name='dog',
        ),
        migrations.AddField(
            model_name='dog',
            name='call_name',
            field=models.CharField(default='Storm', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CallName',
        ),
        migrations.AddField(
            model_name='nicknames',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogdb.Dog'),
        ),
    ]
